version: "3.8"

services:
  # nestjs-app:
  #   image: node:20-alphine
  #   container_name: nestjs-app
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "13000:3000"
  #   command: sh -c "npm install && npm run start:dev"
  #   depends_on:
  #     - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_test_db
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
